# Generated by Django 4.2.5 on 2023-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_productpurchase_learningsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearning',
            name='watched_sec',
            field=models.IntegerField(default=0),
        ),
    ]
